# This file defines the requirements for a productive project deployment.
# It should not contain dependencies for tests, developer tools, etc. (see environment-dev.yml)
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - PyYAML=5.*
  - pandas=1.3.*
  - numpy=1.21
  - matplotlib=3.4.*
  - seaborn=0.11.*
  - scikit-learn=0.24.*
